Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,8 +29,14 @@ jobs:
         run: |
           curl -L -o AIRSDKManager.pkg https://github.com/airsdk/airsdkmanager-releases/releases/download/v1.1.2/AIRSDKManager_1.1.2.pkg
           sudo installer -pkg AIRSDKManager.pkg -target /
-          export PATH="/usr/local/bin:$PATH"
-          sdkmanager install latest --os macos --output airsdk
+          SDK_MANAGER_PATH=$(sudo find / -name sdkmanager 2>/dev/null)
+          if [[ -z "$SDK_MANAGER_PATH" ]]; then
+            echo "::error::sdkmanager executable not found after installation."
+            exit 1
+          fi
+          echo "Found sdkmanager at: $SDK_MANAGER_PATH"
+          "$SDK_MANAGER_PATH" install latest --os macos --output airsdk
+
 
 
       - name: Build Unsigned IPA with ADT
